"""add field_recommendations table

Revision ID: f604ba3f7e68
Revises: ae38b819375b
Create Date: 2026-07-30 23:25:04.939132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f604ba3f7e68'
down_revision: Union[str, Sequence[str], None] = 'ae38b819375b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('zones_rec', sa.JSON(), nullable=False),
    sa.Column('short_zone_rec', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_recommendations')
    # ### end Alembic commands ###
